<?xml version="1.0"?>
<package format="3">
  <name>interface</name>
  <version>0.0.1</version>
  <description>ROS 2 waypoint service interface for boat.</description>
  <maintainer email="ericcai32@gmail.com">ericcai32</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
